[Dispatcher-influx]
type = "SandboxFilter"
filename = "filters/dispatcher.lua"
message_matcher = "Type == 'heka.statmetric'"
    [Dispatcher-influx.config]
    list = "label1"
    label1_regex = "."
    label1_sandbox = "5s-avg"

[Dispatcher-trwebclient]
type = "SandboxFilter"
filename = "filters/dispatcher.lua"
message_matcher = "Type == 'heka.statmetric'"
    [Dispatcher-trwebclient.config]
    list = "label1"
    label1_regex = "."
    label1_sandbox = "collect"

[Trwebclient-filter]
type = "SandboxFilter"
filename = "filters/collect_data.lua"
message_matcher = "Type == 'heka.sandbox.collect'"
ticker_interval = 2

[Cbufs-5s-avg]
type = "SandboxFilter"
filename = "filters/operation.lua"
message_matcher = "Type == 'heka.sandbox.5s-avg'"
ticker_interval = 5
    [Cbufs-5s-avg.config]
    aggregation = "avg"
    sec_per_row = 5
    nb_rows = 10
