[InfluxDispatcherFilter]
type = "SandboxFilter"
filename = "/home/helioslite/heka-hl-sandboxes/toml/filters/dispatcher.lua"
message_matcher = "Type == 'heka.statmetric'"
    [InfluxDispatcherFilter.config]
    matchers = "label1"
    label1_regex = ".*"
    label1_type_output = "5s-avg"

[TrwebclientDispatcherFilter]
type = "SandboxFilter"
filename = "/home/helioslite/heka-hl-sandboxes/toml/filters/dispatcher.lua"
message_matcher = "Type == 'heka.statmetric'"
    [TrwebclientDispatcherFilter.config]
    matchers = "label1"
    label1_regex = ".*"
    label1_type_output = "collect"

[Trwebclient-filter]
type = "SandboxFilter"
filename = "/home/helioslite/heka-hl-sandboxes/toml/filters/collect_data.lua"
message_matcher = "Type == 'heka.sandbox.collect'"
ticker_interval = 2

[Cbufs-5s-avg]
type = "SandboxFilter"
filename = "/home/helioslite/heka-hl-sandboxes/toml/filters/operation.lua"
message_matcher = "Type == 'heka.sandbox.5s-avg'"
ticker_interval = 5
    [Cbufs-5s-avg.config]
    aggregation = "avg"
    sec_per_row = 5
    nb_rows = 10
