[SetModeFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_PLUGINS_BASE_DIR]/filters/add_mode_field.lua"
message_matcher = "Type == 'heka.statmetric'"
    [SetModeFilter.config]
    type_output = "dispatch"

[ParkDispatchFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_PLUGINS_BASE_DIR]/filters/regex_dispatch_metric.lua"
message_matcher = "Type == 'heka.sandbox.dispatch' && Fields[mode] == 2"
    [ParkDispatchFilter.config]
    matchers = "allMetrics"
    allMetrics_regex = ".*"
    allMetrics_type_output = "1h.avg"

[15mLastFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_PLUGINS_BASE_DIR]/filters/aggregate_metric.lua"
message_matcher = "Type == 'heka.sandbox.1h.avg'"
ticker_interval = 3600
    [15mLastFilter.config]
    aggregation = "avg"
    type_output = "addFields"

[NoParkDispatchFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_PLUGINS_BASE_DIR]/filters/regex_dispatch_metric.lua"
message_matcher = "Type == 'heka.sandbox.dispatch' && (Fields[mode] != 2 || Fields[mode] == NIL)"
    [NoParkDispatchFilter.config]
    matchers = "windMetric allMetrics"
    allMetrics_regex = ".*"
    allMetrics_type_output = "5s.avg"
    windMetric_regex = ".*wind"
    windMetric_type_output = "3s.avg"

[5sAvgFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_PLUGINS_BASE_DIR]/filters/aggregate_metric.lua"
message_matcher = "Type == 'heka.sandbox.5s.avg'"
ticker_interval = 5
    [5sAvgFilter.config]
    aggregation = "avg"
    type_output = "addFields"

[Gust3sAvgFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_PLUGINS_BASE_DIR]/filters/aggregate_metric.lua"
message_matcher = "Type == 'heka.sandbox.3s.avg'"
ticker_interval = 3
    [Gust3sAvgFilter.config]
    aggregation = "avg"
    type_output = "60s.max"

[Gust60sMaxFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_PLUGINS_BASE_DIR]/filters/aggregate_metric.lua"
message_matcher = "Type == 'heka.sandbox.60s.max'"
ticker_interval = 60
    [Gust60sMaxFilter.config]
    aggregation = "max"
    type_output = "addFields"
