[InfluxDispatcherFilter]
type = "SandboxFilter"
filename = "/home/helioslite/heka-hl-sandboxes/toml/filters/dispatcher.lua"
message_matcher = "Type == 'heka.statmetric'"
    [InfluxDispatcherFilter.config]
    matchers = "label1"
    label1_regex = ".*"
    label1_type_output = "5s-avg"

[TrwebclientDispatcherFilter]
type = "SandboxFilter"
filename = "/home/helioslite/heka-hl-sandboxes/toml/filters/dispatcher.lua"
message_matcher = "Type == 'heka.statmetric'"
    [TrwebclientDispatcherFilter.config]
    matchers = "label1"
    label1_regex = ".*"
    label1_type_output = "collect"

[Cbufs-5s-avg]
type = "SandboxFilter"
filename = "/home/helioslite/heka-hl-sandboxes/toml/filters/operation.lua"
message_matcher = "Type == 'heka.sandbox.5s-avg'"
ticker_interval = 5
    [Cbufs-5s-avg.config]
    aggregation = "avg"
    sec_per_row = 5
    nb_rows = 10
    type_output = "addFields"

[SetUuidHostnameFilter]
type = "SandboxFilter"
filename = "/home/helioslite/heka-hl-sandboxes/toml/filters/to_fields.lua"
message_matcher = "Type == 'heka.sandbox.addFields'"
    [SetUuidHostnameFilter.config]
    matchers = "uuid hostname"
    uuid = "d539a1ab-1742-43c5-982e-02fab58283fa"
    hostname = "hl-mc-1-dev"
    type_output = "output"

[TrwebclientFilter]
type = "SandboxFilter"
filename = "/home/helioslite/heka-hl-sandboxes/toml/filters/operation.lua"
message_matcher = "Type == 'heka.sandbox.collect'"
ticker_interval = 1
    [TrwebclientFilter.config]
    aggregation = "last"
    type_output = "trwebclient"
