[IddleFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_PLUGINS_BASE_DIR]/heka-hl-sandboxes/toml/filters/park_dispatch_metric.lua"
message_matcher = "Type == 'heka.statmetric'"
    [IddleFilter.config]
    type_output = "dispatch"
    park_type_output = "dispatch.discard"

[MainDispatchFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_PLUGINS_BASE_DIR]/heka-hl-sandboxes/toml/filters/regex_dispatch_metric.lua"
message_matcher = "Type == 'heka.sandbox.dispatch'"
    [MainDispatchFilter.config]
    matchers = "windMetric allMetrics"
    allMetrics_regex = ".*"
    allMetrics_type_output = "5s.avg"
    windMetric_regex = ".*wind"
    windMetric_type_output = "3s.avg"

[5sAvgFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_PLUGINS_BASE_DIR]/heka-hl-sandboxes/toml/filters/aggregate_metric.lua"
message_matcher = "Type == 'heka.sandbox.5s.avg'"
ticker_interval = 5
    [5sAvgFilter.config]
    aggregation = "avg"
    type_output = "addFields"

[Gust3sAvgFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_PLUGINS_BASE_DIR]/heka-hl-sandboxes/toml/filters/aggregate_metric.lua"
message_matcher = "Type == 'heka.sandbox.3s.avg'"
ticker_interval = 3
    [Gust3sAvgFilter.config]
    aggregation = "avg"
    type_output = "60s.max"

[Gust60sMaxFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_PLUGINS_BASE_DIR]/heka-hl-sandboxes/toml/filters/aggregate_metric.lua"
message_matcher = "Type == 'heka.sandbox.60s.max'"
ticker_interval = 60
    [Gust60sMaxFilter.config]
    aggregation = "max"
    type_output = "addFields"

[SetUuidHostnameFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_PLUGINS_BASE_DIR]/heka-hl-sandboxes/toml/filters/add_static_fields.lua"
message_matcher = "Type == 'heka.sandbox.addFields'"
    [SetUuidHostnameFilter.config]
    fields = "uuid hostname"
    uuid = "d539a1ab-1742-43c5-982e-02fab58283fa"
    hostname = "hl-mc-1-dev"
    type_output = "output"

[TrwebclientDispatcherFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_PLUGINS_BASE_DIR]/heka-hl-sandboxes/toml/filters/regex_dispatch_metric.lua"
message_matcher = "Type == 'heka.statmetric'"
    [TrwebclientDispatcherFilter.config]
    matchers = "label1"
    label1_regex = ".*"
    label1_type_output = "collect"

[60sLastFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_PLUGINS_BASE_DIR]/heka-hl-sandboxes/toml/filters/aggregate_metric.lua"
message_matcher = "Type == 'heka.sandbox.collect'"
ticker_interval = 1
    [60sLastFilter.config]
    aggregation = "last"
    type_output = "group"

[GroupMetricsFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_PLUGINS_BASE_DIR]/heka-hl-sandboxes/toml/filters/gather_last_metrics.lua"
message_matcher = "Type == 'heka.sandbox.group'"
ticker_interval = 1
    [GroupMetricsFilter.config]
    type_output = "trwebclient"
