[Dispatcher]
type = "SandboxFilter"
filename = "filters/dispatcher.lua"
message_matcher = "Type == 'heka.statmetric.decoder'"
    [Dispatcher.config]
    list = "label1"
    label1_regex = "trserver_sun_roll"
    label1_sandbox = "5s-avg"

[Cbufs-5s-avg]
type = "SandboxFilter"
filename = "filters/operation.lua"
message_matcher = "Type == 'heka.sandbox.5s-avg'"
ticker_interval = 5
    [Cbufs-5s-avg.config]
    aggregation = "avg"
    sec_per_row = 5
    nb_rows = 10
