[StatsdpInput]
type = "UdpInput"
address = "localhost:8125"
splitter = "TokenSplitter"
decoder = "StatsdpDecoder"

[StatsdpDecoder]
type = "SandboxDecoder"
filename = "%ENV[HEKA_HL_DIR]/lua_decoders/decode_statsdp.lua"
    [StatsdpDecoder.config]
    type_output = "statsdp.metric"
