[hekad]
max_message_loops = 10
maxprocs = 4

# Heka listens to localhost:5565 for Heka ACL protobuf messages
[TCP:5565]
type = "TcpInput"
address = "localhost:5565"
splitter = "ACLSplitter"

[ACLSplitter]
type = "HekaFramingSplitter"
    [ACLSplitter.signer.SandboxManager_0]
    hmac_key = "TODO: changeme"

[SandboxManager]
type = "SandboxManagerFilter"
message_signer = "SandboxManager"
max_filters = 100
