[hekad]
max_message_loops = 5

[PlatformDevs]
type = "SandboxManagerFilter"
message_signer = "PlatformDevs"
max_filters = 100
[TCP:5565]
type = "TcpInput"
parser_type = "message.proto"
decoder = "ProtobufDecoder"
address = ":5565"
    [TCP:5565.signer.PlatformDevs_0]
    hmac_key = "Platform devs signing key"

[TrServerDecoder]
type = "SandboxDecoder"
filename = "/home/helioslite/heka-hl-sandboxes/toml/decoders/trserver.lua"
    [TrServerDecoder.config]
    type_output = "heka.statmetric"
[TrServerInput]
type = "UdpInput"
address = "0.0.0.0:8125"
parser_type = "regexp"
delimiter = "\n"
decoder = "TrServerDecoder"

[Statmetric-influx-preEncoder]
type = "SandboxFilter"
filename = "/home/helioslite/heka-hl-sandboxes/toml/filters/to_influx.lua"
message_matcher = "Type == 'heka.sandbox.output'"
[Statmetric-influx-encoder]
type = "SandboxEncoder"
filename = "lua_encoders/statmetric_influx.lua"
[InfluxOutput]
type = "HttpOutput"
message_matcher = "Type == 'heka.sandbox.influx'"
address = "http://localhost:8086/db/metrics/series"
username = "admin"
password = "admin_password"
encoder = "Statmetric-influx-encoder"

[ServerEncoder]
type = "SandboxEncoder"
filename = "/home/helioslite/heka-hl-sandboxes/toml/encoders/to_server.lua"
[ServerOutput]
type = "HttpOutput"
message_matcher = "Type == 'heka.sandbox.trwebclient'"
address = "http://localhost:8888/heka"
encoder = "ServerEncoder"
[ServerOutput.headers]
Content-Type = ["application/json"]
