[hekad]
share_dir = "/home/helioslite/heka-hl-sandboxes/toml"

[PlatformDevs]
type = "SandboxManagerFilter"
message_signer = "PlatformDevs"
max_filters = 100
[TCP:5565]
type = "TcpInput"
parser_type = "message.proto"
decoder = "ProtobufDecoder"
address = ":5565"
    [TCP:5565.signer.PlatformDevs_0]
    hmac_key = "Platform devs signing key"

[TrserverParse]
type = "SandboxDecoder"
filename = "filters/trserver.lua"
    [TrserverParse.config]
    uuid = "uuid"
    masterController = "masterController"
[Trserver]
type = "UdpInput"
address = "0.0.0.0:8125"
parser_type = "regexp"
delimiter = "\n"
decoder = "TrserverParse"

[Statmetric-influx-preEncoder]
type = "SandboxFilter"
filename = "filters/to_influx.lua"
message_matcher = "Type == 'heka.sandbox.output'"
[Statmetric-influx-encoder]
type = "SandboxEncoder"
filename = "lua_encoders/statmetric_influx.lua"
[Influx]
type = "HttpOutput"
message_matcher = "Type == 'heka.sandbox.influx'"
address = "http://localhost:8086/db/metrics/series"
username = "admin"
password = "admin_password"
encoder = "Statmetric-influx-encoder"

[ServerDatabase]
type = "SandboxEncoder"
filename = "encoders/to_server.lua"
[Server]
type = "HttpOutput"
message_matcher = "Type == 'heka.sandbox.trwebclient'"
address = "http://localhost:8888/heka"
encoder = "ServerDatabase"
[Server.headers]
Content-Type = ["application/json"]
