[hekad]
share_dir = "/config/toml"

[TrserverParse]
type = "SandboxDecoder"
filename = "filters/trserver.lua"
    [TrserverParse.config]
    uuid = "uuid"
[Trserver]
type = "UdpInput"
address = "0.0.0.0:8125"
parser_type = "regexp"
delimiter = "\n"
decoder = "TrserverParse"

[Output]
type = "SandboxFilter"
filename = "filters/to_influx.lua"
message_matcher = "Type == 'heka.sandbox.output'"

[Statmetric-influx-encoder]
type = "SandboxEncoder"
filename = "lua_encoders/statmetric_influx.lua"
[Influx]
type = "HttpOutput"
message_matcher = "Type == 'heka.sandbox.influx'"
address = "http://influxdb:8086/db/metrics/series"
username = "admin"
password = "admin_password"
encoder = "Statmetric-influx-encoder"
