[hekad]
max_message_loops = 6
max_timer_inject = 100

[PlatformDevs]
type = "SandboxManagerFilter"
message_signer = "PlatformDevs"
max_filters = 100
[AclSplitter]
type = "HekaFramingSplitter"
[AclSplitter.signer.PlatformDevs_0]
hmac_key = "Platform devs signing key"
[TCP:5565]
type = "TcpInput"
address = ":5565"
splitter = "AclSplitter"

[TrServerDecoder]
type = "SandboxDecoder"
filename = "%ENV[HEKA_HL_DIR]/decoders/trserver_decode_metrics.lua"
    [TrServerDecoder.config]
    type_output = "heka.statmetric"
[TrServerInput]
type = "UdpInput"
address = "localhost:8125"
splitter = "TokenSplitter"
decoder = "TrServerDecoder"

[TrwebclientDecoder]
type = "SandboxDecoder"
filename = "%ENV[HEKA_HL_DIR]/decoders/trwebclient_decode_event.lua"
    [TrwebclientDecoder.config]
    type_output = "trwebclient.log.event"
[TrwebclientInput]
type = "HttpListenInput"
address = "localhost:5000"
decoder = "TrwebclientDecoder"
