[SetUuidHostnameInfluxFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_PLUGINS_BASE_DIR]/heka-hl-sandboxes/toml/filters/add_static_fields.lua"
message_matcher = "Type == 'heka.sandbox.addFields'"
    [SetUuidHostnameInfluxFilter.config]
    fields = "uuid hostname"
    uuid = "d539a1ab-1742-43c5-982e-02fab58283fa"
    hostname = "hl-mc-1-dev"
    type_output = "encode.influx"

[InfluxPreEncoderFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_PLUGINS_BASE_DIR]/heka-hl-sandboxes/toml/filters/format_metric_name.lua"
message_matcher = "Type == 'heka.sandbox.encode.influx'"
    [InfluxPreEncoderFilter.config]
    fields = "uuid hostname name"
    separator = "."
    emit_timestamp_in_sec = true
    type_output = "influx"
[InfluxEncoder]
type = "SandboxEncoder"
filename = "lua_encoders/statmetric_influx.lua"
[InfluxOutput]
type = "HttpOutput"
message_matcher = "Type == 'heka.sandbox.influx'"
address = "http://localhost:8086/db/metrics/series"
username = "admin"
password = "admin_password"
encoder = "InfluxEncoder"
