[SetModeFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_PLUGINS_BASE_DIR]/heka-hl-sandboxes/toml/filters/add_mode_field.lua"
message_matcher = "Type == 'heka.statmetric'"
    [SetModeFilter.config]
    type_output = "dispatch"

[15mLastFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_PLUGINS_BASE_DIR]/heka-hl-sandboxes/toml/filters/aggregate_metric.lua"
message_matcher = "Type == 'heka.sandbox.dispatch' && Fields[mode] == '2'"
ticker_interval = 900
    [15mLastFilter.config]
    aggregation = "last"
    type_output = "addFields"

[MainDispatchFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_PLUGINS_BASE_DIR]/heka-hl-sandboxes/toml/filters/regex_dispatch_metric.lua"
message_matcher = "Type == 'heka.sandbox.dispatch'"
    [MainDispatchFilter.config]
    matchers = "windMetric allMetrics"
    allMetrics_regex = ".*"
    allMetrics_type_output = "5s.avg"
    windMetric_regex = ".*wind"
    windMetric_type_output = "3s.avg"

[5sAvgFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_PLUGINS_BASE_DIR]/heka-hl-sandboxes/toml/filters/aggregate_metric.lua"
message_matcher = "Type == 'heka.sandbox.5s.avg'"
ticker_interval = 5
    [5sAvgFilter.config]
    aggregation = "avg"
    type_output = "addFields"

[Gust3sAvgFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_PLUGINS_BASE_DIR]/heka-hl-sandboxes/toml/filters/aggregate_metric.lua"
message_matcher = "Type == 'heka.sandbox.3s.avg'"
ticker_interval = 3
    [Gust3sAvgFilter.config]
    aggregation = "avg"
    type_output = "60s.max"

[Gust60sMaxFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_PLUGINS_BASE_DIR]/heka-hl-sandboxes/toml/filters/aggregate_metric.lua"
message_matcher = "Type == 'heka.sandbox.60s.max'"
ticker_interval = 60
    [Gust60sMaxFilter.config]
    aggregation = "max"
    type_output = "addFields"

[SetUuidHostnameFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_PLUGINS_BASE_DIR]/heka-hl-sandboxes/toml/filters/add_static_fields.lua"
message_matcher = "Type == 'heka.sandbox.addFields'"
    [SetUuidHostnameFilter.config]
    fields = "uuid hostname"
    uuid = "d539a1ab-1742-43c5-982e-02fab58283fa"
    hostname = "hl-mc-1-dev"
    type_output = "encode.influx"

[Statmetric-influx-preEncoder]
type = "SandboxFilter"
filename = "%ENV[HEKA_PLUGINS_BASE_DIR]/heka-hl-sandboxes/toml/filters/format_metric_name.lua"
message_matcher = "Type == 'heka.sandbox.encode.influx'"
    [Statmetric-influx-preEncoder.config]
    fields = "uuid hostname name"
    separator = "."
    emit_timestamp_in_sec = true
    type_output = "influx"
[Statmetric-influx-encoder]
type = "SandboxEncoder"
filename = "lua_encoders/statmetric_influx.lua"
[InfluxOutput]
type = "HttpOutput"
message_matcher = "Type == 'heka.sandbox.influx'"
address = "http://localhost:8086/db/metrics/series"
username = "admin"
password = "admin_password"
encoder = "Statmetric-influx-encoder"
