[SetUuidHostnameInfluxFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_HL_DIR]/filters/add_static_fields.lua"
message_matcher = "Type == 'heka.sandbox.addFields'"
    [SetUuidHostnameInfluxFilter.config]
    fields = "uuid hostname"
    uuid = "d539a1ab-1742-43c5-982e-02fab58283fa"
    hostname = "hl-mc-1-dev"
    type_output = "encode.name"

[FormatMetricNameFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_HL_DIR]/filters/format_metric_name.lua"
message_matcher = "Type == 'heka.sandbox.encode.name'"
    [FormatMetricNameFilter.config]
    fields = "uuid hostname name"
    separator = "."
    type_output = "gather.metrics"

[GatherMetrics]
type = "SandboxFilter"
filename = "%ENV[HEKA_HL_DIR]/filters/gather_metrics.lua"
message_matcher = "Type == 'heka.sandbox.gather.metrics'"
ticker_interval = 20
    [GatherMetrics.config]
    type_output = "influx"

[PayloadEncoder]
[InfluxOutput]
type = "HttpOutput"
message_matcher = "Type == 'heka.sandbox.influx'"
address = "http://localhost:8086/db/metrics/series?time_precision=u"
username = "admin"
password = "admin_password"
encoder = "PayloadEncoder"
