[DecodeLogMetricFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_PLUGINS_BASE_DIR]/heka-hl-sandboxes/toml/filters/decode_metric.lua"
message_matcher = "Type == 'log.input'"
    [DecodeLogMetricFilter.config]
    type_output = "login"

[DecodeLogAlertFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_PLUGINS_BASE_DIR]/heka-hl-sandboxes/toml/filters/decode_alert.lua"
message_matcher = "Type == 'log.input'"
    [DecodeLogAlertFilter.config]
    type_output = "login"

[DecodeLogEventFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_PLUGINS_BASE_DIR]/heka-hl-sandboxes/toml/filters/decode_event.lua"
message_matcher = "Type == 'log.input'"
    [DecodeLogEventFilter.config]
    type_output = "login"

[LogFileDecoder]
type = "SandboxDecoder"
filename = "%ENV[HEKA_PLUGINS_BASE_DIR]/heka-hl-sandboxes/toml/decoders/decode_header.lua"
    [LogFileDecoder.config]
    type_output = "log.input"
[LogFileInput]
type = "LogstreamerInput"
log_directory = "%ENV[HEKA_PLUGINS_BASE_DIR]/heka-hl-sandboxes/log"
file_match = "file.log"
parser_type = "regexp"
delimiter = "\n"
decoder = "LogFileDecoder"
