[SetUuidHostnameLogFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_HL_DIR]/filters/add_static_fields.lua"
message_matcher = "Type == 'heka.sandbox.addFields' || Type == 'trwebclient.log.event'"
    [SetUuidHostnameLogFilter.config]
    fields = "uuid hostname"
    uuid = "d539a1ab-1742-43c5-982e-02fab58283fa"
    hostname = "hl-mc-1-dev"
    type_output = "log.message"

[EncodeMetricFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_HL_DIR]/filters/encode_metric.lua"
message_matcher = "Type == 'heka.sandbox.log.message' && Fields[type] == NIL"
    [EncodeMetricFilter.config]
    type_output = "log.output"

[EncodeEventFilter]
type = "SandboxFilter"
filename = "%ENV[HEKA_HL_DIR]/filters/encode_event.lua"
message_matcher = "Type == 'heka.sandbox.log.message' && Fields[type] == 'event'"
    [EncodeEventFilter.config]
    type_output = "log.output"

[LogFileEncoder]
type = "SandboxEncoder"
filename = "%ENV[HEKA_HL_DIR]/encoders/encode_header.lua"
[LogFileOutput]
type = "FileOutput"
message_matcher = "Type == 'heka.sandbox.log.output'"
path = "%ENV[HEKA_HL_DIR]/log/file.log"
encoder = "LogFileEncoder"

[LogFileCarbonEncoder]
type = "SandboxEncoder"
filename = "%ENV[HEKA_HL_DIR]/encoders/encode_carbon.lua"
[LogFileCarbonOutput]
type = "FileOutput"
message_matcher = "Type == 'heka.sandbox.log.message' && Fields[type] == NIL"
path = "%ENV[HEKA_HL_DIR]/log/carbon.log"
encoder = "LogFileCarbonEncoder"
